---

- name: Create aws directory structure
  file:
    state: directory
    path: "{{ lab_common_credentils_aws_cred_path }}"
    mode: '0700'

- name: Template aws
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0700'
  with_items:
    - { src: config.j2, dest: "{{ lab_common_credentils_aws_cred_path }}/config" }
    - { src: credentials.j2, dest: "{{ lab_common_credentils_aws_cred_path }}/credentials" }
